server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-cpb6khnsc6pc73a3hhh0-a.oregon-postgres.render.com/schema_portgressql_sql?user=schema_portgressql_sql_user&password=gT1KHQtN1fyY0qiZdt7WgstZTMA9NnWH
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            schema-locations: classpath:schema-postgresql.sql
            mode: always
            platform: postgres

logging:
    level:
        root: INFO
        org.springframework: DEBUG
        org.hibernate: DEBUG
